= Quiz

== 질문 1.

=== 프로그밍 언어의 구문(syntax)과 의미론(semantics)이 무엇을 의미하는지 간략하게 설명하라. 구문 오류와 의미론 오류 간의 차이를 보여주는 예를 들어보라

답변: +
syntax는 각 언어마다의 지켜야하는 언어의 규칙을 의미한다. +
Semantics는 해당 프로그래밍의 문장이 뜻하는 구문의 의미를 나타낸다 +
구문 오류는 java에서 출력을 의미하는 System.out.println이 아닌 printf를 +
사용하는 것이 구문 오류이다. +
의미론 오류는 사용자가 출력을 의미하기위해서 System.out.println을 해야하는데+ 입력을 받는 scanner.next()와 같은 입력을 받는 구문을 사용하는 것을 의미론 오류라고 한다. +

== 질문 2

=== 컴퓨터가 변수 선언문을 실행할 때 무엇을 하는가? 예를 들어보라

답: +
int num = 0; 이라는 Expression이 있다면, 변수의 데이터 타입인 +
int를 정의하고 해당하는 메모리 주소 이름에 num 저장한 담에, 주소가 담고있는 결과값에 0을 넣는다. +

== 짐루 3

=== 프로그래밍과 관련이 있는 용어인 자료형(type)이란 무엇인가?

답: +
자료형이란 변수를 선언할 때 변수 안에 저장할 데이터의 값이 종류를 의미한다.

== 질문 4

=== 자바에서 가장 원시적인 자료형 중 하나는 부울(boolean)이다. boolean 자료형은 무엇인가? 부울 값은 어디에 사용되는가?

답: +
조건문의 식의 결과를 변수에 담을 때 사용한다. boolean의 값은 주로 if문과 같은 조건문에 사용이 +
된다. boolean의 가능한 값은 true와 false이다.

== 질문 5

=== 다음 각 자바 연산자의 의미를 들어보라: a) ++ b) && c)!=

답: +
a)는 자료형의 값에 +1을해주는 연산자이다 b)는 조건문에서 and 연산자로 두 식의 값이 true일 때 true를 반환해주는 의미를 가짐 +
c)는 x != 1이라는 식을 예시로 들면 x가 1이 아닐 때 true라는 값을 반환하고, x가 1일 때는 false를 반환한다.

== 질문 6

=== 할당문(assignment statement)이 의미하는 바를 설명하고, 예를 들어보라. 할당문은 무엇에 사용되는가?

답: +
할당문은 변수에 값을 참조하는 것을 의미한다. 예로 int x = 1를 의미함

== 질문 7

=== 연산자의 우선순위(precedence)는 무엇을 의미하는가?

답: +
컴퓨터가 연산을 실행할 때 가장 먼저 연산을 진행하는 우선 순위를 의미한다. +
보통은 식의 왼쪽부터 연산을 진행하지만 ()가 있다면 ()를 먼저 연산한다.

== 질문 8

=== 리터럴(literal)이란 무엇인가?

답: +
자바에서 리터럴은 상수를 의미한다.

== 질문 9

=== 자바에서 클래스는 근본적으로 두 가지 목적을 가지고 있다. 무엇인가?

답: +
1. 사용자가 원하는 자료형을 만들기위해서 2. 객체를 참조하기위해서 +
정답: +
1. 클래스에 포함된 변수와 서브루틴을 그룹화, 이를 클래스의 정적 멤버라고함 2. 객체를 설명하고 생성하는 것,클래스는 해당 객체 포함된 변수와 서브루틴을 지정

== 질문 10

=== 다음 문장들 사이에는 어떤 차이점이 있는가? x=TextIO.getDouble(); 및 x = TextIO.getlnDouble();

답: +
처음 식은 x에 double값 하나만 저장만 하는 것이고, 두 번쨰 식은 x에 double값을 저장한 후 nextline을 해준다.

== 질문 11

=== 표현식 2 + 3 "test"의 값은 문자열 "5test"인 반면 표현식 "test" + 2 + 3의 값은 문자열 "test23"인 이유를 설명하라.

답: +
연산자 우선순위로 인해 2+3의 값인 5가 나온 다음에 문자열인 test에 덧셈 연산자가 된 것이므로 5test가 된것이고 +
test+2+3은 test+2가 먼저 연산이 되므로 문자열의 값인 test23이 된다.

== 질문 13

=== import textio.TextIO 또는 import java.util.Scanner와 같은 가져오기(import) 명령어의 목적은 무엇인가?

답: +
해당 클래스의 메소드를 참조하기위해서 import를 해준다.

== 질문 14

